language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: A3lzZE6jthwOdNWg/ziRxAtwwcvSyidtDnlleEsectdxvvylLxxRhqIpwExGdvCp15xqjrxwB/6AdlII9NmSA/ZJloF/Sa8joXpy20jawYD+EbukaHhjLJ6j/9FQ3C0ElvviYo7pW2vNzb0AXlpGf8P17TTx5XxGPmAFdujDT0U=
  app: skittles
  on:
    repo: TheSkittles/TicTacToe
