language: java
jdk: oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - build/install/TicTacToe/bin/TicTacToe  # start project
  - sleep 3 # give spark some time to bind to sockets, etc

deploy:
  provider: heroku
  api_key:
    secure: A3lzZE6jthwOdNWg/ziRxAtwwcvSyidtDnlleEsectdxvvylLxxRhqIpwExGdvCp15xqjrxwB/6AdlII9NmSA/ZJloF/Sa8joXpy20jawYD+EbukaHhjLJ6j/9FQ3C0ElvviYo7pW2vNzb0AXlpGf8P17TTx5XxGPmAFdujDT0U=
  app: skittles
  on:
    repo: TheSkittles/TicTacToe
