package is.skittles.tictactoe;

import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'eggert' at '10/25/14 2:33 PM' with Gradle 2.1
 *
 * @author eggert, @date 10/25/14 2:33 PM
 */
public class TicTacToeTest {
    @Test public void testSomethingBogus() {
        TicTacToe classUnderTest = new TicTacToe();
        assertTrue("True should be true", true);
    }
}