package is.skittles.tictactoe;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eggert' at '10/25/14 2:33 PM' with Gradle 2.1
 *
 * @author eggert, @date 10/25/14 2:33 PM
 */
public class TicTacToe {
    public static void main(String[] args) {
        System.out.println("Hello world!");
        return;
    }
}
